language: node_js
node_js:
  - "node"

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

after_success:
  cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - echo "skipping tests"
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release 